[package]
name = "nft_marketplace"
edition = "2024"         # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]
version = "0.0.1"

# Removed explicit Sui dependency to enable automatic handling

[addresses]
nft_marketplace = "0x0"
example = "0x0"
devhub = "0x0"